### ISSUE TITLE
Support mechanism for this package

### ISSUE THREAD

**Issue by tigloo** [juancastillo0/graphql_server#18]
What is the support mechanism for this package? It's great and surprisingly complete, but only one person seems to be committing. Is there any support community around this package?

**Comment by juancastillo0** [comment]
Mainly thought this Github. The GraphQL community in Dart can in found in https://discord.com/invite/vYtZuAjrVr . You can ask questions there or through issues in this repository.

**Comment by tigloo** [comment]
Thanks! I'll close it as it seems like this is not the right thing to track in an issue. Could you resend the invitation link? It seems the first one timed out already.
